{
	"commentStamp" : "JulienDelplanque 6/9/2017 10:25",
	"super" : "Error",
	"category" : "Python3Generator-Errors",
	"classinstvars" : [ ],
	"pools" : [ ],
	"classvars" : [ ],
	"instvars" : [ ],
	"name" : "P3GPythonException",
	"type" : "normal"
}